name: New Field Note
description: Create a new field note entry
title: "[Note] "
labels: ["note"]
body:
  - type: input
    id: project
    attributes:
      label: Project
      description: "Which project is this note for?"
      placeholder: "e.g., Bridgeport Rebuild, F350 Diagnostics"
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags
      description: "Comma-separated tags"
      placeholder: "e.g., welding, diesel, electrical"
    validations:
      required: false

  - type: textarea
    id: body
    attributes:
      label: Note Body
      description: "The content of your note. Markdown supported."
      placeholder: "Write your note here..."
    validations:
      required: true
